accessibility: protected
containerPort: 5000

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 1
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /
    port: 5000
  periodSeconds: 5

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits: # hard limits
    cpu: 100m
    memory: 128Mi
